ci improvements (#64)
* ci: improve gh releasing conditions in workflow. added RELEASING.md. symlink priv dir in docker image

* ci: run checks workflow on any push exept main with a pushed tag

* replace git.long with semver in rebar.config

* run feature.yml on every push

* trigger acion on pull request to main

* trigger acion on pull request to main

diff --git a/.github/workflows/xqerl.yml b/.github/workflows/xqerl.yml
--- a/.github/workflows/xqerl.yml
+++ b/.github/workflows/xqerl.yml
@@ -1,27 +1,57 @@
+# https://docs.github.com/en/actions/learn-github-actions/expressions
 name: build check release
 on:
   push:
     branches: 'main'
     tags:
-      - 'v*'
+      - 'v*.*.*'
   pull_request:
-    branches:
-      - '**:**'
+    branches: 'main'
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - name: checkout repo
-      uses: actions/checkout@v2
-      with:
-        fetch-depth: 1
+      uses: actions/checkout@v3
+    - name: set env
+      run: |
+        grep -qoP 'v\d+\.\d+\.\d+' rebar.config
+        grep -qoP '\d+\.\d+\.\d+' src/xqerl.app.src
+        REBAR_RELEASE="$(grep -oP 'v\d+\.\d+\.\d+' rebar.config)"
+        APP_VSN="$(grep -oP '\d+\.\d+\.\d+' src/xqerl.app.src)"
+        echo "rebar_release=$REBAR_RELEASE" >> $GITHUB_ENV
+        echo "app_vsn=$APP_VSN" >> $GITHUB_ENV
+    - name: when branch do some inital checks
+      if:  ${{ github.ref_type == 'branch'  }} 
+      run: |
+        echo ${{github.ref_name}}
+        echo 'check: rebar_release and app_vsn have the same version number'
+        ${{ env.rebar_release == format('{0}{1}','v', env.app_vsn ) }}
+        echo " - rebar_release: ${{ env.rebar_release}} "
+        echo " - xqerl app vsn: ${{ env.app_vsn }} "
+    - name: when tag do some inital checks
+      if:  ${{ github.ref_type == 'tag'  }} 
+      run: |
+        echo " - release version: ${{github.ref_name}}"
+        # - derive NOTE from the annotated tag message
+        NOTE="$(git tag -l --format='%(contents:subject)' ${{github.ref_name}} )"
+        echo " - release subject: ${NOTE}"
+        echo 'check: rebar_release and app_vsn have the same version number'
+        ${{ env.rebar_release == format('{0}{1}','v', env.app_vsn ) }} 
+        echo 'check: tag version is the same as rebar release version'
+        ${{ env.rebar_release == github.ref_name }} 
+        echo 'check: annotated tag  will have tag message '
+        # A pushed tag may be lightwieght tag therefor no subject
+        [ ! -z "${NOTE}" ] || echo 'ERR: lightweight tag pushed. use annotated tag to create release'
+        [ ! -z "${NOTE}" ]
+        #echo " - rebar_release: ${{ env.rebar_release}} "
+        #echo " - xqerl app vsn: ${{ env.app_vsn }} "
     - name: Cache dependencies
       id: cache-deps
       uses: actions/cache@v2
       with:
         path: _build
         key: rebar-${{ hashFiles('./rebar.lock') }}
-        # restore-keys: rebar-
     - name: Cache dependencies
       if: steps.cache-deps.outputs.cache-hit != 'true'
       run: |
@@ -30,46 +60,42 @@ jobs:
     - name: build production tar
       run: |
         rebar3 as prod tar
-        mkdir _release
-        mv _build/prod/rel/xqerl/*.tar.gz _release/xqerl.tar.gz
+        mv _build/prod/rel/xqerl/xqerl-*.tar.gz ./xqerl.tar.gz
     - name: Upload built artifact
-      uses: actions/upload-artifact@v2
+      uses: actions/upload-artifact@v3
       with:
         name: xqerl-prod-tar
-        path: _release/
+        path: ./xqerl.tar.gz
   checks:
     if: ${{ github.ref_type == 'branch' }}
     needs: build
     runs-on: ubuntu-latest
     steps:
     - name: checkout repo
-      uses: actions/checkout@v2
-      with:
-        fetch-depth: 0
+      uses: actions/checkout@v3
     - name: Download built artifact
-      uses: actions/download-artifact@v2
+      uses: actions/download-artifact@v3
       with:
         name: xqerl-prod-tar
     - name: Unpack release tar and install xqerl application
       run: |
         mkdir -p  $HOME/.local/xqerl
         mkdir -p  $HOME/.local/bin
+        # echo "$HOME/.local/bin" >> $GITHUB_PATH
         tar -zxf xqerl.tar.gz -C $HOME/.local/xqerl
         ln -s $HOME/.local/xqerl/bin/xqerl $HOME/.local/bin
-        ls -al $HOME/.local/bin
-        echo $PATH
         which xqerl
     - name: Start the xqerl application
       run: |
         xqerl daemon
         sleep 2
         xqerl eval 'application:ensure_all_started(xqerl).'
-    - name: Checks - OTP Beam inspection 
+    - name: Checks - OTP Beam inspection
       run: |
           printf %60s | tr ' ' '-' && echo
-          echo -n '-  ping: ' 
+          echo -n '-  ping: '
           xqerl ping | grep -oP 'pong'
-          echo -n '-  pid: ' 
+          echo -n '-  pid: '
           xqerl pid | grep -oP '\d+'
           printf %60s | tr ' ' '-' && echo
           echo -n ' - set xqerl working directory: '
@@ -110,53 +136,39 @@ jobs:
     - name: Stop xqerl
       run: xqerl stop
   release:
-    if: ${{ github.ref_type == 'tag' }}    
+    if: ${{ github.ref_type == 'tag' }}
     needs: build
     runs-on: ubuntu-latest
     steps:
     - name: checkout repo
-      uses: actions/checkout@v2
-      with:
-        fetch-depth: 1
-    - name: Fetch tags
-      run: |
-        git fetch --force --tags
-        git describe --abbrev=0 || true
-        printf %60s | tr ' ' '-' && echo
+      uses: actions/checkout@v3
     - name: Download built artifact
-      uses: actions/download-artifact@v2
+      uses: actions/download-artifact@v3
       with:
         name: xqerl-prod-tar
     - name: Release artifact
-      run: |
-        VERSION=$(echo ${RELEASE} | sed s/v// )
-        NOTE="$(git tag -l --format='%(contents:subject)' ${RELEASE})"
-        # note is annotated tag message
-        mv ./xqerl.tar.gz  ./xqerl-${VERSION}.tar.gz
-        gh release create ${RELEASE} "./xqerl-${VERSION}.tar.gz#xqerl-${VERSION}" \
-        --notes "${NOTE}"  \
-        --title "xqerl release ${RELEASE}" \
-        --target  ${SHA}
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        OWNER: ${{ github.repository_owner }}
-        SHA: ${{github.sha}}
-        RELEASE: ${{github.ref_name}}
-        #MESSAGE: ${{ github.event.head_commit.message }}
+      run: |
+        echo " - release version: ${{github.ref_name}}"
+        # - derive NOTE from the annotated tag message
+        NOTE="$(git tag -l --format='%(contents:subject)' ${{github.ref_name}} )"
+        echo " - release note: ${NOTE}"
+        # in build we detirmined that rebar.config version is the same as pushed annotated tag
+        # so we can just use ${{github.ref_name}} for the release name
+        # mv ./xqerl.tar.gz  ./xqerl-${{github.ref_name}}.tar.gz
+        # use the gh client to create release
+        gh release create ${{github.ref_name}} "./xqerl.tar.gz#xqerl ${{github.ref_name}}" \
+        --notes "${NOTE}"  \
+        --title "xqerl release ${{github.ref_name}}" \
+        --target ${{github.sha}}
   package:
-    if: ${{ github.ref_type == 'tag' }}    
+    if: ${{ github.ref_type == 'tag' }}
     needs: build
     runs-on: ubuntu-latest
     steps:
     - name: checkout repo
-      uses: actions/checkout@v2
-      with:
-        fetch-depth: 0
-    - name: Fetch tags
-      run: |
-        git fetch --force --tags
-        git describe --abbrev=0 || true
-        printf %60s | tr ' ' '-' && echo
+      uses: actions/checkout@v3
     - name: Fetch the cached _build
       id: cache-deps
       uses: actions/cache@v2
@@ -165,28 +177,27 @@ jobs:
         key: rebar-${{ hashFiles('./rebar.lock') }}
     - name: Buildah build
       run: |
-        VERSION=$(echo "${RELEASE}" | sed s/v// )
         ALPINE_VERSION=3.15
         ERLANG_VERSION=24.3-alpine
-        echo "version: $VERSION"
-        echo " - build from alpine version: $ALPINE_VERSION "
+        echo " - release version: ${{github.ref_name}}"
+        echo " - build from alpine version: $(ALPINE_VERSION)"
+        echo " - uses erlang version: $(ERLANG_VERSION)"
         BASE_CONTAINER=$(buildah from docker.io/erlang:${ERLANG_VERSION})
         buildah copy ${BASE_CONTAINER} ./ /home/
         buildah run ${BASE_CONTAINER} sh -c 'apk add --update git tar \
         && cd /home \
         && rebar3 as prod tar \
         && mkdir /usr/local/xqerl \
-        && tar -zxf _build/prod/rel/*/*.tar.gz -C /usr/local/xqerl'
+        && tar -zxf _build/prod/rel/xqerl/xqerl-${{github.ref_name}}.tar.gz -C /usr/local/xqerl'
         CONTAINER=$(buildah from docker.io/alpine:${ALPINE_VERSION})
         buildah run ${CONTAINER} sh -c 'apk add --no-cache openssl ncurses-libs tzdata libstdc++ \
         && mkdir /usr/local/xqerl \
         && cd /usr/local/bin \
         && ln -s /usr/local/xqerl/bin/xqerl'
-        buildah copy --from ${BASE_CONTAINER} $CONTAINER /usr/local/xqerl /usr/local/xqerl  
+        buildah copy --from ${BASE_CONTAINER} $CONTAINER /usr/local/xqerl /usr/local/xqerl 
         printf %60s | tr ' ' '-' && echo
         echo " -  check"
-        buildah run ${CONTAINER} sh -c 'ls -al /usr/local/bin | grep -q xqerl'
-        buildah run ${CONTAINER} sh -c 'which xqerl' # should error if fails to find   
+        buildah run ${CONTAINER} sh -c 'which xqerl' # should error if fails to find  
         echo " - set working dir and entry point"
         buildah config --cmd '' ${CONTAINER}
         buildah config --workingdir /usr/local/xqerl ${CONTAINER}
@@ -201,12 +212,14 @@ jobs:
         echo " - set stop signal"
         buildah config --stop-signal SIGQUIT ${CONTAINER}
         echo " - set labels"
-        buildah config --label org.opencontainers.image.base.name=alpine:${ALPINE_VERSION} ${CONTAINER} 
+        buildah config --label org.opencontainers.image.base.name=alpine:${ALPINE_VERSION} ${CONTAINER}
         buildah config --label org.opencontainers.image.title='xqerl' ${CONTAINER}
         buildah config --label org.opencontainers.image.description='Erlang XQuery 3.1 Processor and XML Database' ${CONTAINER}
         buildah config --label org.opencontainers.image.source=https://github.com/${GITHUB_REPOSITORY} ${CONTAINER} # where the image is built
         buildah config --label org.opencontainers.image.documentation=https://github.com//${GITHUB_REPOSITORY} ${CONTAINER} # image documentation
-        buildah config --label org.opencontainers.image.version='${VERSION}' ${CONTAINER} # version
+        buildah config --label org.opencontainers.image.version='${{github.ref_name}}' ${CONTAINER} # version
+        buildah run ${CONTAINER} sh -c \
+        'xqerl daemon && sleep 2 && xqerl eval "file:make_symlink(code:priv_dir(xqerl),\"./priv\")." && xqerl stop'
         buildah commit --rm ${CONTAINER} localhost/xqerl
         printf %60s | tr ' ' '-' && echo
         echo " - list docker images"
@@ -221,14 +234,11 @@ jobs:
         printf %60s | tr ' ' '-' && echo
         podman logs -n -t --since 0 -l
         printf %60s | tr ' ' '-' && echo
-        echo -n ' - check running: ' 
+        echo -n ' - check running: '
         podman container inspect -f '{{.State.Running}}' xq
         podman exec xq xqerl eval "application:ensure_all_started(xqerl)."
         podman ps -a
         podman stop xq || true
-      env:
-        SHA: ${{github.sha}}
-        RELEASE: ${{github.ref_name}}
     - name: Login to GitHub Container Registry
       uses: docker/login-action@v1
       with:
@@ -237,27 +247,23 @@ jobs:
         password: ${{ secrets.GITHUB_TOKEN }}
     - name: Push to GitHub Container Registry
       run: |
-        VERSION=$(echo "${RELEASE}" | sed s/v// )
-        echo " - tag image - ghcr.io/${GITHUB_REPOSITORY}:${VERSION}"
-        buildah tag localhost/xqerl ghcr.io/${GITHUB_REPOSITORY}:${VERSION}
-        buildah push ghcr.io/${GITHUB_REPOSITORY}:${VERSION}
-      env:
-        RELEASE: ${{github.ref_name}}
+        buildah tag localhost/xqerl ghcr.io/${GITHUB_REPOSITORY}:${{github.ref_name}}
+        buildah push ghcr.io/${GITHUB_REPOSITORY}:${{github.ref_name}}
     - name: Login to Docker Container Registry
+      env:
+        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
       if: "${{ env.DOCKER_TOKEN != '' }}"
       uses: docker/login-action@v1
       with:
         registry: docker.io
         username: ${{ github.actor }}
         password: ${{ secrets.DOCKER_TOKEN }}
+    - name: Push to Docker Container Registry
       env:
         DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
-    - name: Push to Docker Container Registry
       if: "${{ env.DOCKER_TOKEN != '' }}"
       run: |
-        VERSION=$(echo "${RELEASE}" | sed s/v// )
-        buildah tag localhost/xqerl docker.io/${GITHUB_REPOSITORY}:${VERSION}
-        buildah push docker.io/${GITHUB_REPOSITORY}:${VERSION}
-      env:
-        RELEASE: ${{github.ref_name}}
-        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
+        buildah tag localhost/xqerl docker.io/${GITHUB_REPOSITORY}:${{github.ref_name}}
+        buildah push docker.io/${GITHUB_REPOSITORY}:${{github.ref_name}}
+        buildah tag localhost/xqerl docker.io/${GITHUB_REPOSITORY}:latest
+        buildah push docker.io/${GITHUB_REPOSITORY}:latest
